# Generated by Django 4.2.3 on 2023-11-09 00:53

import apps.val_practice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, validators=[apps.val_practice.models.validateLenGreaterThanTwo])),
                ('last_name', models.CharField(max_length=100, validators=[apps.val_practice.models.validateLenGreaterThanTwo])),
                ('username', models.CharField(max_length=100, validators=[apps.val_practice.models.validateLenGreaterThanTwo])),
                ('password', models.CharField(max_length=100, validators=[apps.val_practice.models.validateLenGreaterThanSeven])),
                ('email', models.CharField(max_length=100, validators=[apps.val_practice.models.validateEmail])),
            ],
        ),
    ]
